name: generate animation
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v0.0.18
        with:
          github_user_name: amycardoso
          svg_out_path: dist/github-contribution-grid-snake.svg
