name: generate animation
on: 
  schedule:
      # Runs at 01:00 UTC every day
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update activity
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: amycardoso
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
