name: generate animation

on:
  schedule:
      # every 12 hours
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: amycardoso
          svg_out_path: dist/github-contribution-grid-snake.svg
